name: cd-dgraph
on:
  workflow_dispatch:
    inputs:
      latest:
        type: boolean
        default: false
        description: release latest tag docker-images on dockerhub
      releasetag:
        description: releasetag
        required: true
        type: string
jobs:
  dgraph-build-amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.releasetag }}'
      - name: Make Dgraph Docker Image
        run: |
          echo "no latest"
          [[ "${{ inputs.latest }}" = true ]] && echo "latest" || true
